### ISSUE TITLE
gRPC streaming with envoy wasm

### ISSUE THREAD

**Issue by NomadXD** [salrashid123/envoy_wasm#1]
Thanks a lot for the example of envoy wasm filter with gRPC unary request. Have you tried it with gRPC streaming ? In the proto file, you have defined a server streaming service but couldn't find any implementation. I'm trying to use gRPC bidi streaming. I have a native C++ filter that I want to re-implement as WASM.

**Comment by NomadXD** [comment]
what's so confusing is 
`auto res = root()->grpcStreamHandler(grpc_service_string, EchoServerServiceName, PublishMetadataMethodName, initial_metadata,std::unique_ptr<GrpcStreamHandlerBase>(new MyGrpcCallStreamHandler(this)));`  
returns a `WasmResult`. So if we are using a grpc streaming from a filter we have to ,
```cpp

MyGrpcCallStreamHandler streamHandler_ = new MyGrpcCallStreamHandler(this);
auto res = root()->grpcStreamHandler(grpc_service_string, EchoServerServiceName,EchoMethodName, initial_metadata,std::unique_ptr<GrpcStreamHandlerBase>(streamHandler_));

```
from onCreate in context.

and then implement some methods in `MyGrpcCallStreamHandler` to make it possible for the ExampleFilter to call the send method in `MyGrpcCallStreamHandler`. Is that the correct way to do it ?

**Comment by NomadXD** [comment]
I would be so thankful if you can provide a sample code snippet since there's no any other examples related to this and I'm blocked here for couple of days.

**Comment by salrashid123** [comment]
i really don't know cpp that well at all to construct a sample  but you would use [grpcStreamHandler()](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/master/docs/wasm_filter.md#grpcstreamhandler)  as the way to get this done.

what i'm not sure which mode you need (server,client or bidi) but that function should be the thing to use.

i know go better so i'm going to update this snippet once [proy-wasm-go-sdk#14](https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/14) is addressed

**Comment by NomadXD** [comment]
For me the issue is not with using  grpcStreamHandler(). See these 2 method definitions for example. 

```cpp

WasmResult grpcCallHandler(std::string_view service, std::string_view service_name,
                             std::string_view method_name,
                             const HeaderStringPairs &initial_metadata, std::string_view request,
                             uint32_t timeout_milliseconds,
                             std::unique_ptr<GrpcCallHandlerBase> handler);

```

And for the streamHandler() 

```cpp
WasmResult grpcStreamHandler(std::string_view service, std::string_view service_name,
                               std::string_view method_name,
                               const HeaderStringPairs &initial_metadata,
                               std::unique_ptr<GrpcStreamHandlerBase> handler);
```
For unary calls, that method directly sends the request. But for streams that method just create a stream and we have to implement another class by inheriting from GrpcStreamHandler and use their send() method to send a request. 

```cpp
class MyGrpcCallStreamHandler : public GrpcStreamHandler<google::protobuf::Value, google::protobuf::Value>
```
What I don't understand is how to call that method from the filter class. For the native filter I pass a reference to StreamHandler in the constructor of the filter. Here I'm not sure where to pass that. Maybe from on the onCreate() method of the filter. Thanks for the response.
